spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
redis.enabled=false
spring.data.redis.host=localhost
spring.data.redis.port=6379
jwt-key=cai-secretkey-nay-dung-de-test-thoi-khong-dung-thuc-te-va-yeu-cau-do-dai-secret-512bit
jwt.access.token.expiration=3600
jwt.refresh.token.expiration=604800
firebase.config.path=/home/dang-phong/Desktop/MyProject/secret/firebase-secret.json
mapbox.access-token=temp_test_access_token
mapbox.base-url=https://api.mapbox.com
shop.location.lat=10.862778663635254
shop.location.lng=106.80362606048584
vnpay.tmnCode=temp_test_tmnCode
vnpay.hashSecret=temo_test_hashSecret
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=test
spring.mail.password=test
twilio.account.sid=temp_test_account_sid
twilio.auth.token=temp_test_auth_token
twilio.verify.sid=temp_test_verify_sid
storage.root.location=/home/dang-phong/Desktop/MyProject/storage
admin.username=test
admin.password=password
admin.phone=0123456789
admin.email=test@gmail.com
